/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;


import Reproductor.MetaDatos;
import Reproductor.Opciones;
import estructurasgenerictp1.Diccionarios;
import estructurasgenerictp1.LQueue;
import j.DoubleLinkedList;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Ricardo A
 */
public class Grafica extends javax.swing.JFrame implements Runnable {
    
    
    
    
    /**
     * Creates new form Configuracion
     */
    public Grafica() {
        
        
        this.setTitle("TecMusic");
        initComponents();
        this.setLocationRelativeTo(null);
        Reproductor=new Opciones();
        cola=new Diccionarios();
        
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Play = new javax.swing.JButton();
        Stop = new javax.swing.JButton();
        Cancion = new javax.swing.JButton();
        Atras = new javax.swing.JButton();
        Siguiente = new javax.swing.JButton();
        PalabraBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        OpcionesBusqueda = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        EtiLetra = new javax.swing.JLabel();
        EtiCancion = new javax.swing.JLabel();
        EtiArtista = new javax.swing.JLabel();
        EtiAlbum = new javax.swing.JLabel();
        EtiGenero = new javax.swing.JLabel();
        EtiDuracion = new javax.swing.JLabel();
        ListaArtista = new java.awt.List();
        ListaCancion = new java.awt.List();
        ListaDuracion = new java.awt.List();
        ListaAlbum = new java.awt.List();
        ListaGenero = new java.awt.List();
        ListaCancion2 = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Play.jpg"))); // NOI18N
        Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayActionPerformed(evt);
            }
        });

        Stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/stop.jpg"))); // NOI18N
        Stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopActionPerformed(evt);
            }
        });

        Cancion.setText("Agregar");
        Cancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancionActionPerformed(evt);
            }
        });

        Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.jpg"))); // NOI18N

        Siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/siguiente.jpg"))); // NOI18N
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });

        PalabraBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PalabraBuscarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N

        OpcionesBusqueda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Artista", "Album", "Genero", "Cancion" }));

        jButton2.setText("Eliminar");

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        EtiLetra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EtiLetra.setForeground(new java.awt.Color(0, 0, 255));
        EtiLetra.setText("Letra");

        EtiCancion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EtiCancion.setText("Canción");

        EtiArtista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EtiArtista.setText("Artistas");

        EtiAlbum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EtiAlbum.setText("Álbum");

        EtiGenero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EtiGenero.setText("Genero");

        EtiDuracion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EtiDuracion.setText("Duración");

        ListaAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaAlbumActionPerformed(evt);
            }
        });

        ListaGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaGeneroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(Cancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(202, 202, 202)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Play, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EtiCancion)
                        .addGap(161, 161, 161)
                        .addComponent(EtiArtista)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Stop, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PalabraBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OpcionesBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addComponent(EtiAlbum)
                        .addGap(153, 153, 153)
                        .addComponent(EtiGenero)
                        .addGap(142, 142, 142)
                        .addComponent(EtiDuracion)
                        .addGap(87, 87, 87))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ListaCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ListaArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ListaAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ListaGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ListaDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ListaCancion2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(395, 395, 395))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(EtiLetra)
                        .addGap(605, 605, 605))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(PalabraBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(OpcionesBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Play, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(Siguiente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Stop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Cancion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EtiCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EtiGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EtiDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EtiArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EtiAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ListaArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ListaCancion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ListaDuracion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(ListaAlbum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(ListaGenero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                        .addGap(19, 19, 19)
                        .addComponent(EtiLetra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ListaCancion2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancionActionPerformed
        JFileChooser dig = new JFileChooser();  //Crea un objeto de dialogo JFileChooser
        FileNameExtensionFilter ex=new FileNameExtensionFilter("MP3","mp3");
        dig.setMultiSelectionEnabled(rootPaneCheckingEnabled);
        dig.setFileFilter(ex);
        int option = dig.showOpenDialog(this);  // Abre la ventana en dialogo
        if (option == JFileChooser.APPROVE_OPTION){
            //System.out.println(dig.getFileView());
            
            try {
                String file = dig.getSelectedFile().getPath();  //Obtener ruta y nombre al hacer click
                //Muestra nombre del archivo
                RutaAnterior=Ruta;
                Ruta=file;
                System.out.println(file);
                
                if(FlagCancion==false){
                    Reproductor.Open(Ruta);
                    MetaDatos temp=new MetaDatos();
                    temp.meta(Ruta);

                    Reproductor.Play();
                    FlagCancion=true;
                    cola.put(temp.getTitulo(),Ruta,temp.getArtista(),temp.getAlbum(),temp.getgenero(),temp.getduracionMin());
                    System.out.println(cola.size());
                    ListaCancion.add(temp.getTitulo());
                    ListaArtista.add(temp.getArtista());
                    ListaAlbum.add(temp.getAlbum());
                    ListaGenero.add(temp.getgenero());
                    double total = temp.getduracionMin();
                    String total2 = String.valueOf(total);
                    ListaDuracion.add(total2);
                    
                }
                else{
                    Reproductor.Continue();
                    MetaDatos temp=new MetaDatos();
                    temp.meta(Ruta);
                    
                    cola.put(temp.getTitulo(),Ruta,temp.getArtista(),temp.getAlbum(),temp.getgenero(),temp.getduracionMin());
                    System.out.println(cola.size());
                    ListaCancion.add(temp.getTitulo());
                    ListaArtista.add(temp.getArtista());
                    ListaAlbum.add(temp.getAlbum());
                    ListaGenero.add(temp.getgenero());
                    double total = temp.getduracionMin();
                    String total2 = String.valueOf(total);
                    ListaDuracion.add(total2);
                }
                //canc=dig.getSelectedFiles();
                /**if(canc.length>1){
                    System.out.println(Ruta=file);
                    for(int i=0;i<canc.length;i++){
                        System.out.println(canc[i]);
                    }
                    
                    System.out.println(direc);
                    }
                else{
                    Ruta=file;
                    System.out.println(Ruta);
                }**/
                
            } catch (Exception e) {
                System.out.println("Hola");
                return;
            }
        }       
    }//GEN-LAST:event_CancionActionPerformed

    private void PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayActionPerformed
        try {
            if(FlagCancion==true){
                Reproductor.Pause();
                FlagCancion=false;
            }
            else{
                Reproductor.Continue();
                FlagCancion=true;
            }
            
        } catch (Exception ex) {
            System.out.println("error");
            Logger.getLogger(Grafica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PlayActionPerformed

    private void StopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopActionPerformed
        try {
            Reproductor.Stop();
            FlagCancion=false;
        } catch (Exception ex) {
            Logger.getLogger(Grafica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_StopActionPerformed

    private void PalabraBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PalabraBuscarActionPerformed
        
    }//GEN-LAST:event_PalabraBuscarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        System.out.println(cola.getPos()+"AAA");
        System.out.println(cola.size()+"AAA");
        if(cola.getPos()<cola.size()-1){
            System.out.println(cola.getPos()+"BBB");
            try {
                
                String ruta=(String) cola.getRuta();
                try {
                    Reproductor.Open(ruta);
                } catch (Exception ex) {
                    Logger.getLogger(Grafica.class.getName()).log(Level.SEVERE, null, ex);
                }
                Reproductor.Play();
                
            } 
            catch (NullPointerException ex) {
                try {
                    Reproductor.Stop();
                } catch (Exception ex1) {
                    Logger.getLogger(Grafica.class.getName()).log(Level.SEVERE, null, ex1);
                }
                return;
            } catch (Exception ex) {
                Logger.getLogger(Grafica.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        else{
            System.out.println(cola.getPos()+"8888811111");
            System.out.println(cola.size()+"sxkv");
            cola.goToStart();
            
            System.out.println(cola.getPos()+"''''''");
            String ruta=(String) cola.getRuta();
            try {
                Reproductor.Open(ruta);
            } catch (Exception ex) {
                Logger.getLogger(Grafica.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                Reproductor.Play();
            } catch (Exception ex) {
                Logger.getLogger(Grafica.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        
        
        
    }//GEN-LAST:event_SiguienteActionPerformed

    private void ListaAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaAlbumActionPerformed

    private void ListaGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaGeneroActionPerformed
    
    
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton Cancion;
    private javax.swing.JLabel EtiAlbum;
    private javax.swing.JLabel EtiArtista;
    private javax.swing.JLabel EtiCancion;
    private javax.swing.JLabel EtiDuracion;
    private javax.swing.JLabel EtiGenero;
    private javax.swing.JLabel EtiLetra;
    private java.awt.List ListaAlbum;
    private java.awt.List ListaArtista;
    private java.awt.List ListaCancion;
    private java.awt.List ListaCancion2;
    private java.awt.List ListaDuracion;
    private java.awt.List ListaGenero;
    private javax.swing.JComboBox OpcionesBusqueda;
    private javax.swing.JTextField PalabraBuscar;
    private javax.swing.JButton Play;
    private javax.swing.JButton Siguiente;
    private javax.swing.JButton Stop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
    boolean FlagCancion=false;
    Opciones Reproductor;
    String Ruta=null;
    String RutaAnterior=null;
    File[] canc;
    String direc;
    Diccionarios cola;
    
    
    
    
    
    
    
    
    
    
    
    
    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafica().setVisible(true);
            }
        });
    }
}
